-- Avios Destination Review — switch from plugin-owned storage to a CMS content type.
-- After this migration, every generated review lives as an entry of the "Destinations"
-- content type (public route /destinations/{slug}). adr_reviews keeps its rows as a
-- thin link table (iata -> entry_id) with generation provenance (model, prompt).

-- 1. Create the "Destinations" content type if it doesn't exist yet.
INSERT INTO cms_content_types (name, slug, icon, description, has_public_route, supports_seo, supports_featured_image)
SELECT 'Destinations', 'destinations', 'plane-departure', 'Avios destination reviews — one entry per British Airways destination.', 1, 1, 1
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM cms_content_types WHERE slug = 'destinations');

-- 2. Create the rich-text "Article body" field if it doesn't exist yet.
INSERT INTO cms_content_fields (content_type_id, label, field_key, field_type, placeholder, help_text, is_required, sort_order)
SELECT t.id, 'Article body', 'body', 'richtext', NULL, 'Main article HTML. Generated by the Avios Destination Review plugin; safe to hand-edit.', 0, 10
FROM cms_content_types t
WHERE t.slug = 'destinations'
  AND NOT EXISTS (
    SELECT 1 FROM cms_content_fields f
    WHERE f.content_type_id = t.id AND f.field_key = 'body'
  );

-- 3. Create the IATA text field if it doesn't exist yet.
INSERT INTO cms_content_fields (content_type_id, label, field_key, field_type, placeholder, help_text, is_required, sort_order)
SELECT t.id, 'IATA code', 'iata', 'text', 'e.g. JFK', '3-letter airport code from the How Many Avios fare table.', 0, 5
FROM cms_content_types t
WHERE t.slug = 'destinations'
  AND NOT EXISTS (
    SELECT 1 FROM cms_content_fields f
    WHERE f.content_type_id = t.id AND f.field_key = 'iata'
  );

-- 4. Link adr_reviews to cms_content_entries via entry_id.
ALTER TABLE adr_reviews ADD COLUMN entry_id INT UNSIGNED DEFAULT NULL AFTER iata;
ALTER TABLE adr_reviews ADD KEY idx_entry_id (entry_id);

-- 5. Backfill: create a content entry for every existing review that isn't linked yet.
INSERT INTO cms_content_entries (content_type_id, title, slug, status, seo_title, seo_description, published_at, created_at, updated_at)
SELECT
  (SELECT id FROM cms_content_types WHERE slug = 'destinations'),
  a.destination,
  a.slug,
  'published',
  a.meta_title,
  a.meta_description,
  IFNULL(a.created_at, CURRENT_TIMESTAMP),
  a.created_at,
  a.updated_at
FROM adr_reviews a
WHERE a.entry_id IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM cms_content_entries e
    WHERE e.content_type_id = (SELECT id FROM cms_content_types WHERE slug = 'destinations')
      AND e.slug = a.slug
  );

-- 6. Link adr_reviews.entry_id to the entries we just created (or any pre-existing match).
UPDATE adr_reviews a
JOIN cms_content_entries e
  ON e.slug = a.slug
  AND e.content_type_id = (SELECT id FROM cms_content_types WHERE slug = 'destinations')
SET a.entry_id = e.id
WHERE a.entry_id IS NULL;

-- 7. Backfill the body field value for each linked entry.
INSERT INTO cms_content_entry_values (content_entry_id, field_id, value_longtext)
SELECT a.entry_id,
       (SELECT f.id FROM cms_content_fields f
        WHERE f.content_type_id = (SELECT id FROM cms_content_types WHERE slug = 'destinations')
          AND f.field_key = 'body'),
       a.content_html
FROM adr_reviews a
WHERE a.entry_id IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM cms_content_entry_values v
    WHERE v.content_entry_id = a.entry_id
      AND v.field_id = (SELECT f.id FROM cms_content_fields f
                        WHERE f.content_type_id = (SELECT id FROM cms_content_types WHERE slug = 'destinations')
                          AND f.field_key = 'body')
  );

-- 8. Backfill the iata field value too.
INSERT INTO cms_content_entry_values (content_entry_id, field_id, value_longtext)
SELECT a.entry_id,
       (SELECT f.id FROM cms_content_fields f
        WHERE f.content_type_id = (SELECT id FROM cms_content_types WHERE slug = 'destinations')
          AND f.field_key = 'iata'),
       a.iata
FROM adr_reviews a
WHERE a.entry_id IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM cms_content_entry_values v
    WHERE v.content_entry_id = a.entry_id
      AND v.field_id = (SELECT f.id FROM cms_content_fields f
                        WHERE f.content_type_id = (SELECT id FROM cms_content_types WHERE slug = 'destinations')
                          AND f.field_key = 'iata')
  );
